---
title: "Witchcraft"
author: |
  |
  | Bruno Rucy Carneiro Alves de Lima, Joonas Järve
  | University of Tartu, Institute of Computer Science
  | bruno98@ut.ee
abstract: "Doing witchcraft"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=0.80in
fontsize: 11pt
fontfamily: mathpazo
spacing: single
output: 
  pdf_document:
    keep_tex: true
#classoption:
#- twocolumn
header-includes:
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}\Large\bfseries}
  - \posttitle{\end{flushleft}}  
  - \predate{\begin{flushright}\large}
  - \postdate{\end{flushright}}
  - \preauthor{\begin{flushleft}\Large}
  - \postauthor{\end{flushleft}}  
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = F, fig.height = 4, fig.width = 6)
library(reticulate)
use_python("/home/rucy/python_environments/algorithmics/bin/python3.8")
import_builtins()
import_main()
library(microbenchmark)
library(purrr)
library(dplyr)
library(ggplot2)
library(stringi)
```

## Making the functions

```{python}

import random as rand
import math

def getRandomLevel(p = 0.5):
    lvl = 0
    while rand.random() < p: # and lvl < float('inf'):
        lvl = lvl + 1
    return lvl

def getRandomLevelApprox(n = 2):
    return (-n * math.log2(rand.random()))

```

## 10000 Runs

```{r}

one_million_randoms = replicate(100000, expr = py$getRandomLevel(), simplify = FALSE)
one_million_approx_randoms = replicate(100000, expr = py$getRandomLevelApprox(1), simplify = FALSE)

```

## Prepping the data

```{r}

flattened_omr = as.numeric(one_million_randoms)
flattened_omar = as.numeric(one_million_approx_randoms)

cummax_fomr = cummax(flattened_omr)
cummax_fomar = cummax(flattened_omar)

```

## Plotting them

```{r}

hundred_thousand = data.frame(n = seq(from = 1, to = 100000, by = 1),
                              cummax_fomr = cummax_fomr,
                              cummax_fomar = cummax_fomar)

ggplot(data = hundred_thousand, aes(x = n)) +
  theme_minimal() +
  theme(axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"),
        panel.grid.major = element_blank()) +
  geom_line(aes(y = cummax_fomr), color = '#de3d83', size = 2) +
  geom_line(aes(y = cummax_fomar), color = '#00b8b8', size = 2) +
  xlab('Dataset Size') +
  ylab('Maximum height')

```